### ISSUE TITLE
Can't get touch screen to work

### ISSUE THREAD

**Issue by JimVanEeden** [balena-os/balena-raspberrypi#300]
I can not for the life of me get my Raspberry Pi 3 B+ with Raspberry Pi 7" Touchscreen to work. The display is working fine, the touch doesn't work at all. The hardware is not the problem, because it works fine when running on Raspbian. 

The app I'm running is an electron app, based on the electron-react template by you guys. Is this a common problem? If more information is needed I can provide it.

**Comment by floion** [comment]
Hi. Does this touchscreen require any configuration in raspbian?

**Comment by JimVanEeden** [comment]
No I'm actually testing it now and the *exact* thing runs straight away on Raspbian desktop.

**Comment by floion** [comment]
Can you send a link to the exact touchscreen? Amazon link would be nice

**Comment by JimVanEeden** [comment]
It's the official Raspberry Pi 7" Touchscreen:

https://www.kiwi-electronics.nl/7-inch-raspberry-pi-dsi-touchscreen-display?lang=en

**Comment by floion** [comment]
Can you try this example we have? https://github.com/balena-io-projects/balena-dash

**Comment by JimVanEeden** [comment]
Just did, no touch :(

**Comment by floion** [comment]
@dansku can you chime in a bit since you have this working?

**Comment by dansku** [comment]
@JimVanEeden I will setup the project from scratch tomorrow and give you feedback then.
In the meanwhile, could you post a picture of the driver board? I would like just to confirm an make sure it is the same as the one I have here. Cheers

**Comment by floion** [comment]
Maybe it's a similar setup issue as https://github.com/balena-io-projects/balena-wpe/issues/38 ?

**Comment by dansku** [comment]
@JimVanEeden I am running some tests, and this is not a final answer. Could you try setting up a WPE_URL address, this one, for example, https://www.balena.io/blog/page/2/ and see if it the touchscreen works. In case it doesn't work, try rebooting the device (you can do it from the dashboard). After it reboots, can you let me know if it works? On my current tests, after rebooting the touchscreen started working. I will dig more on this today!

**Comment by JimVanEeden** [comment]
Thanks for your help guys, I'm going to try to get it working today!

**Comment by floion** [comment]
@JimVanEeden any luck?

**Comment by JimVanEeden** [comment]
Unfortunately I couldn't get it to work, so for now I'll just be using Raspbian Lite and might try again once our fleet gets too big to manage without your tools.

**Comment by marhoy** [comment]
I have this issue as well, what was the solution?
I just installed balenaos on a rpi3b+ with standard rpi touch screeen

**Comment by floion** [comment]
Hi, what OS version did you try with?

**Comment by marhoy** [comment]
@floion Thanks for following up!
Not sure what I did wrong, but I'm not able to reproduce the issue.
My rpi3b+ with touch screen is currently running the wpe-browser, and all is good :)

**Comment by floion** [comment]
@marhoy that's great news
@JimVanEeden if you still want to give it a shot, please let us know. I now have this display with me so can try and debug your issues if any

**Comment by bitmorse** [comment]
wpe-browser + official Rpi touch screen works here, but the Electron React example does not: display is fine, just no touch.

**Comment by floion** [comment]
@bitmorse can you try and restart the container after it's been started for the first time?

**Comment by bitmorse** [comment]
Here's a video of me restarting the container and showing all config: https://www.icloud.com/photos/#0nIDwE1-k21nzYVU_1lJM-29w

We use the stock balena-react-electron repo with changed react app code (just a few lines) in a multicontainer setup. Our docker-compose.yml:
```yaml
version: '2'
services:
#  balena_wpe:
#    privileged: true
#    build: ./balena-wpe
#    depends_on:
#      - user_app
  electron_frontend:
    build: ./electron-frontend
    network_mode: 'host'
    privileged: true
    ports:
      - 3000:3000
  node_backend:
    build: ./node-backend
    network_mode: 'host' #possibly required for slcan0 to work
    privileged: true
    #restart: always
    ports:
      - 80:80
      - 8080:8080
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/mem:/dev/mem"
      - "/dev/ttyACM0:/dev/ttyACM0"
    cap_add: 
      - SYS_RAWIO
    labels:
          io.balena.features.kernel-modules: '1'
          io.balena.features.firmware: '1'
          io.balena.features.dbus: '1'
          io.balena.features.supervisor-api: '1'
          io.balena.features.balena-api: '1'
          io.balena.update.strategy: download-then-kill
          io.balena.update.handover-timeout: '60000'
```
