### ISSUE TITLE
standard_init_linux.go:195: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by OdysLam** [balena-os/balena-raspberrypi#313]
Greetings,

I have been trying to configure Balena with EdgeX foundry services but with no luck so far.

Image: balenalib/raspberrypi3-64-ubuntu 

every command will produce "standard_init_linux.go:195: exec user process caused "exec format error"" 

Example:

Dockerfile

```
FROM balenalib/raspberrypi3-64-ubuntu
# Create a consul user and group first so the IDs get set the same way, even as
# the rest of this may change over time.

#RUN addgroup consul && \
#   adduser --system --ingroup consul consul

# standard mongo db data dir directories
RUN mkdir /data
RUN mkdir /data/db
RUN echo "this directory is reserved for EdgeX database files" > /data/db/README

# EdgeX shared directories
ENV EDGEX_BASE=/edgex
RUN mkdir $EDGEX_BASE
RUN mkdir $EDGEX_BASE/logs
RUN echo "this directory is reserved for EdgeX log files" > $EDGEX_BASE/logs/README

# Consul config and data directories
# The /consul/data dir is used by Consul to store state. The agent will be started
# with /consul/config as the configuration directory so you can add additional
# config files in that location.
RUN mkdir /consul
RUN mkdir /consul/config
RUN mkdir /consul/data
RUN echo "this directory is reserved for EdgeX Consul config files" > /consul/config/README
RUN echo "this directory is reserved for EdgeX data files" > /consul/data/README
RUN chown -R 100:1000 /consul

COPY static-services-config.json /consul/config

ENTRYPOINT /usr/bin/tail -f /dev/null

```
Compose: 

```
version:` '2.1'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  portainer_data:

services:

  volume:
    build: .
    #   container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      
  consul:
    image: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
#   container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume  
```
